name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Required for auth and database
      BETTER_AUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Prettier check
      - name: Run Prettier check
        run: bun run format:check

      # ESLint check
      - name: Run ESLint
        run: bun run lint

      # Build Next.js project
      - name: Build Next.js project
        run: bun run build
